spring.application.name=todos

spring.datasource.url=jdbc:mysql://localhost:3307/tododb?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=secret

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

springdoc.swagger-ui.path=/docs

spring.jwt.secret=d9fc7d7e29d230fd2f31fe5011b1704d0e5a407ed47197d8173706c52f1dd9f5
spring.jwt.expiration=900000